# This file was generated by GoReleaser. DO NOT EDIT.
class JeedomStatus < Formula
  desc "Jeedom global status for operating systems status bars"
  homepage "https://github.com/deimosfr/jeedom-status"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/deimosfr/jeedom-status/releases/download/v0.6.1/jeedom-status_0.6.1_darwin_amd64.tar.gz"
    sha256 "c86aaec9e39eff4d0d7b02792d7a8a15eaa9f0d674b272e9cb5697b84eb162af"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/deimosfr/jeedom-status/releases/download/v0.6.1/jeedom-status_0.6.1_linux_amd64.tar.gz"
      sha256 "148ed2fedaf081c4f30e7a975127b42eb1950ec1774a36d75451337cc9078481"
    end
  end

  def install
    bin.install "jeedom-status"
  end
end
