# This file was generated by GoReleaser. DO NOT EDIT.
class JeedomStatus < Formula
  desc "Jeedom global status for operating systems status bars"
  homepage "https://github.com/deimosfr/jeedom-status"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/deimosfr/jeedom-status/releases/download/v0.5.0/jeedom-status_0.5.0_darwin_amd64.tar.gz"
    sha256 "9f52e0f371fa140b801978847294cce53800b2e300c551917d22a7b7492ec912"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/deimosfr/jeedom-status/releases/download/v0.5.0/jeedom-status_0.5.0_linux_amd64.tar.gz"
      sha256 "34d32c6576bcda4f758da1037eb656c83dbe571edf6dc898c762eff5e68563df"
    end
  end

  def install
    bin.install "jeedom-status"
  end
end
